WITH baseline(crop_name,variety,family,annual,propagation,direct_sow,transplant,sowing,transplant_months,gmin,gmax,hmin,hmax,water,water_notes,rotation,rotation_notes,spacing,maintenance,harvest,notes) AS (VALUES
('Tomato','Cœur de Bœuf','Solanaceae','annual','Semis en pépinière puis repiquage',true,true,ARRAY[1,2,3],ARRAY[3,4],5,10,75,95,'moderate','Maintenir une humidité régulière sans saturer le sol. Arroser profondément; les besoins augmentent pendant la floraison et le grossissement des fruits.',3,'Éviter de remettre une Solanacée dans cette zone pendant environ 3 ans.','Prévoir assez d’espace pour l’aération, le tuteurage et l’accès.','Prévoir tuteurage, attaches, désherbage et éventuellement paillage.','Récolter lorsque le fruit est coloré et encore ferme.','Fenêtres principales de plein champ près de Sidi Bettach.'),
('Cherry Tomato','Yellow','Solanaceae','annual','Semis en pépinière puis repiquage',true,true,ARRAY[1,2,3],ARRAY[3,4],5,10,60,80,'moderate','Maintenir une humidité régulière sans saturer le sol.',3,'Éviter les Solanacées dans cette zone pendant environ 3 ans.',NULL,'Prévoir un support selon le port de la variété.','Récolter lorsque les fruits sont jaune bien développé et se détachent facilement.',NULL),
('Onion',NULL,'Amaryllidaceae','annual','Semis direct ou pépinière suivie de repiquage',true,true,ARRAY[9,10,11],ARRAY[11,12,1],7,14,100,150,'moderate','Arroser régulièrement pendant l’installation et le grossissement; réduire fortement à maturité.',3,'Éviter les Alliacées dans la même zone pendant environ 3 ans.',NULL,'Maintenir la zone propre; éviter de recouvrir le collet.','Laisser sécher les bulbes avant stockage.',NULL),
('Fava Bean',NULL,'Fabaceae','annual','Semis direct',true,false,ARRAY[10,11,12,1,2],NULL,7,14,80,110,'moderate','Compléter l’arrosage si le sol devient sec, surtout pendant floraison et remplissage des gousses.',3,'Éviter les Fabacées dans la même zone pendant environ 3 ans.','Prévoir environ 20 cm entre plants et de l’espace entre lignes.','Surveiller les pucerons et soutenir les plants si nécessaire.','Récolter les gousses bien formées avant que les graines soient trop dures.',NULL),
('Spaghetti Squash',NULL,'Cucurbitaceae','annual','Semis direct ou jeunes plants repiqués',true,true,ARRAY[4,5,6],ARRAY[4,5,6],4,10,90,110,'high','Arroser profondément et régulièrement, surtout pendant floraison et grossissement. Un paillage peut limiter l’évaporation.',3,'Éviter toute Cucurbitacée dans cette zone pendant environ 3 ans.','Culture coureuse nécessitant beaucoup d’espace.','Guider les tiges si nécessaire et surveiller oïdium, insectes et pollinisation.','Récolter lorsque la peau est dure et le pédoncule commence à sécher.',NULL),
('Pumpkin',NULL,'Cucurbitaceae','annual','Semis direct ou repiquage de jeunes plants',true,true,ARRAY[4,5,6],ARRAY[4,5,6],4,10,90,120,'high','Arroser profondément et régulièrement pendant tiges, floraison et grossissement.',3,'Ne pas remettre de Cucurbitacée dans cette zone pendant environ 3 ans.','Prévoir environ 1,2 m ou davantage selon la variété.','Paillage conseillé; surveiller pollinisation et oïdium.','Récolter lorsque la couleur est développée, la peau dure et le pédoncule sèche.',NULL),
('Courgette','Grise','Cucurbitaceae','annual','Semis direct ou repiquage',true,true,ARRAY[4,5,6],ARRAY[4,5,6],4,8,45,60,'high','Maintenir une humidité régulière avec des arrosages profonds.',3,'Éviter les Cucurbitacées dans cette zone pendant environ 3 ans.','Prévoir environ 80 à 100 cm autour du plant.','Récolter fréquemment et surveiller oïdium et fruits avortés.','Récolter les fruits jeunes et tendres.',NULL),
('Courgette','Verte','Cucurbitaceae','annual','Semis direct ou repiquage',true,true,ARRAY[4,5,6],ARRAY[4,5,6],4,8,45,60,'high','Maintenir une humidité régulière avec des arrosages profonds.',3,'Éviter les Cucurbitacées dans cette zone pendant environ 3 ans.','Prévoir environ 80 à 100 cm autour du plant.','Récolter fréquemment et surveiller oïdium et fruits avortés.','Récolter les fruits jeunes et tendres.',NULL),
('Potato',NULL,'Solanaceae','annual','Plantation de tubercules germés / pommes de terre de semence',false,false,ARRAY[1,2,9,10],NULL,14,28,70,120,'moderate','Maintenir une humidité régulière pendant l’initiation et le grossissement des tubercules; réduire à maturité.',3,'Solanacée : éviter tomate, pomme de terre, poivron ou aubergine pendant environ 3 ans.','Prévoir environ 30 cm entre plants et adapter les rangs au buttage.','Butter progressivement les plants et surveiller le feuillage.','Pour la conservation, attendre la sénescence du feuillage.', 'Les mois indiquent la plantation de tubercules, et non un semis botanique.')
)
UPDATE crop_catalog c SET crop_family=b.family,annual_or_perennial=b.annual,propagation_method=b.propagation,direct_sow_allowed=b.direct_sow,transplant_allowed=b.transplant,sowing_months=b.sowing,transplant_months=b.transplant_months,germination_days_min=b.gmin,germination_days_max=b.gmax,days_to_harvest_min=b.hmin,days_to_harvest_max=b.hmax,watering_level=b.water,watering_notes=b.water_notes,rotation_years=b.rotation,rotation_notes=b.rotation_notes,spacing_notes=b.spacing,maintenance_notes=b.maintenance,harvest_notes=b.harvest,notes=b.notes FROM baseline b WHERE c.crop_name=b.crop_name AND c.variety IS NOT DISTINCT FROM b.variety;
--> statement-breakpoint
INSERT INTO crop_stages (crop_catalog_id,stage_name,sort_order,start_day_estimate,end_day_estimate,expected_observation,recommended_action)
SELECT c.id,s.name,s.ord,s.start_day,s.end_day,s.observation,s.action FROM crop_catalog c CROSS JOIN LATERAL (VALUES
(1,'Levée ou reprise',0,14,'La culture s’installe et de nouvelles pousses apparaissent.','Maintenir une humidité adaptée et vérifier la bonne reprise.'),(2,'Croissance végétative',10,45,'Le feuillage et les tiges se développent activement.','Désherber, surveiller la vigueur et intervenir selon les besoins.'),(3,'Floraison',25,65,'Les fleurs apparaissent ou la culture entre dans sa phase productive.','Maintenir l’irrigation régulière et surveiller l’état général.'),(4,'Formation et grossissement',40,100,'Les organes récoltés se forment ou grossissent progressivement.','Éviter le stress hydrique et poursuivre les observations.'),(5,'Maturation et récolte',70,150,'Les signes de maturité deviennent visibles.','Récolter progressivement au stade souhaité.')
) s(ord,name,start_day,end_day,observation,action) WHERE NOT EXISTS (SELECT 1 FROM crop_stages x WHERE x.crop_catalog_id=c.id);
