"use client";

import { FormEvent, useMemo, useState } from "react";

type Zone = { code: string; name: string; width: number; length: number; notes?: string };
type Seed = { id: number; crop: string; variety?: string; family?: string; status: "in_stock" | "low_stock" | "out_of_stock" | "discontinued"; active: boolean };
type Planting = { id: number; crop: string; variety?: string; family?: string; zone: string; date?: string; precision: "exact" | "approximate" | "unknown"; method: "direct_seed" | "transplanted" | "existing" | "unknown"; status: "planned" | "seeded" | "transplanted" | "growing" | "ready_to_harvest" | "harvesting" | "finished" | "removed"; perennial: boolean; notes?: string };

const zones: Zone[] = [
  ...["RB1", "RB2", "RB3", "RB4"].map((code) => ({ code, name: `Raised Bed ${code.slice(2)}`, width: 3, length: 3 })),
  ...["NB1", "NB2", "NB3", "NB4", "NB5", "NB6", "NB7", "NB8"].map((code) => ({ code, name: `Narrow Bed ${code.slice(2)}`, width: 1, length: 3 })),
  ...Array.from({ length: 10 }, (_, i) => ({ code: `FR${i + 1}`, name: `Front Right ${i + 1}`, width: i === 9 ? 8 : 5, length: 3 })),
  ...Array.from({ length: 10 }, (_, i) => ({ code: `FL${i + 1}`, name: `Front Left ${i + 1}`, width: i === 0 ? 8 : 5, length: 3 })),
  { code: "MF1", name: "Main Field", width: 22, length: 11 },
];

const seededSeeds: Seed[] = [
  ["Tomato", "Cœur de Bœuf", "Solanaceae"], ["Cherry Tomato", "Yellow", "Solanaceae"], ["Onion", "", "Amaryllidaceae"], ["Fava Bean", "", "Fabaceae"], ["Spaghetti Squash", "", "Cucurbitaceae"], ["Pumpkin", "", "Cucurbitaceae"], ["Courgette", "Grise", "Cucurbitaceae"], ["Courgette", "Verte", "Cucurbitaceae"], ["Potato", "", "Solanaceae"],
].map(([crop, variety, family], i) => ({ id: i + 1, crop, variety, family, status: "in_stock", active: true }));

const nav = ["Dashboard", "Farm Map", "Plantings", "Seeds"] as const;
type Page = (typeof nav)[number];
const activeStatuses = ["seeded", "transplanted", "growing", "ready_to_harvest", "harvesting"];

function StatusPill({ status }: { status: string }) { return <span className={`pill ${status}`}>{status.replaceAll("_", " ")}</span>; }
function ZoneGrid({ selected, onSelect, occupied }: { selected?: string; onSelect: (code: string) => void; occupied: Set<string> }) {
  return <div className="zone-grid">{zones.map((z) => <button onClick={() => onSelect(z.code)} key={z.code} className={`zone ${selected === z.code ? "selected" : ""} ${occupied.has(z.code) ? "occupied" : ""}`}><span>{z.code}</span><small>{z.width} × {z.length}m</small></button>)}</div>;
}

export default function Home() {
  const [page, setPage] = useState<Page>("Dashboard");
  const [seeds, setSeeds] = useState(seededSeeds);
  const [plantings, setPlantings] = useState<Planting[]>([]);
  const [selectedZone, setSelectedZone] = useState("RB1");
  const [showSeedForm, setShowSeedForm] = useState(false);
  const [showPlantingForm, setShowPlantingForm] = useState(false);
  const occupied = useMemo(() => new Set(plantings.filter((p) => activeStatuses.includes(p.status)).map((p) => p.zone)), [plantings]);
  const activePlantings = plantings.filter((p) => activeStatuses.includes(p.status));
  const selectZone = (code: string) => { setSelectedZone(code); if (page !== "Farm Map") setPage("Farm Map"); };
  const addSeed = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSeeds((s) => [...s, { id: Date.now(), crop: String(data.get("crop")), variety: String(data.get("variety")) || undefined, family: String(data.get("family")) || undefined, status: "in_stock", active: true }]); setShowSeedForm(false); };
  const addPlanting = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); setPlantings((p) => [...p, { id: Date.now(), crop: String(d.get("crop")), variety: String(d.get("variety")) || undefined, family: String(d.get("family")) || undefined, zone: String(d.get("zone")), date: String(d.get("date")) || undefined, precision: String(d.get("precision")) as Planting["precision"], method: String(d.get("method")) as Planting["method"], status: String(d.get("status")) as Planting["status"], perennial: d.get("perennial") === "on", notes: String(d.get("notes")) || undefined }]); setShowPlantingForm(false); };
  const endPlanting = (id: number, status: "finished" | "removed") => setPlantings((p) => p.map((item) => item.id === id ? { ...item, status } : item));

  return <main className="app-shell"><aside><div className="brand"><span>✦</span><div>Farm Fresh<small>Farm management</small></div></div><nav>{nav.map((item) => <button className={page === item ? "active" : ""} onClick={() => setPage(item)} key={item}>{item}</button>)}</nav><div className="farm-label">SINGLE FARM WORKSPACE<br /><strong>Phase 1 foundation</strong></div></aside><section className="content"><header><div><p className="eyebrow">FARM FRESH</p><h1>{page}</h1></div><button className="quiet">September 2026</button></header>
    {page === "Dashboard" && <Dashboard seeds={seeds} activePlantings={activePlantings} occupied={occupied} onGo={setPage} />}
    {page === "Farm Map" && <MapView selected={selectedZone} onSelect={setSelectedZone} occupied={occupied} plantings={plantings} onAdd={() => setShowPlantingForm(true)} />}
    {page === "Plantings" && <PlantingsView plantings={plantings} onAdd={() => setShowPlantingForm(true)} onEnd={endPlanting} onSelect={selectZone} />}
    {page === "Seeds" && <SeedsView seeds={seeds} setSeeds={setSeeds} onAdd={() => setShowSeedForm(true)} />}
  </section>
  {showSeedForm && <Modal title="Add seed variety" onClose={() => setShowSeedForm(false)}><form onSubmit={addSeed} className="form"><label>Crop name<input required name="crop" autoFocus /></label><label>Variety<input name="variety" /></label><label>Crop family<input name="family" placeholder="Leave blank if unknown" /></label><p className="form-note">Quantity and dates can be added when known.</p><button className="primary">Save seed</button></form></Modal>}
  {showPlantingForm && <Modal title="Record planting" onClose={() => setShowPlantingForm(false)}><form onSubmit={addPlanting} className="form"><div className="form-row"><label>Crop name<input required name="crop" autoFocus /></label><label>Variety<input name="variety" /></label></div><div className="form-row"><label>Zone<select name="zone" defaultValue={selectedZone}>{zones.map((z) => <option key={z.code}>{z.code}</option>)}</select></label><label>Crop family<input name="family" placeholder="Optional" /></label></div><div className="form-row"><label>Planting date<input name="date" type="date" /></label><label>Date precision<select name="precision" defaultValue="unknown"><option value="exact">Exact</option><option value="approximate">Approximate</option><option value="unknown">Unknown</option></select></label></div><div className="form-row"><label>Method<select name="method" defaultValue="existing"><option value="direct_seed">Direct seed</option><option value="transplanted">Transplanted</option><option value="existing">Existing</option><option value="unknown">Unknown</option></select></label><label>Status<select name="status" defaultValue="growing"><option value="planned">Planned</option><option value="seeded">Seeded</option><option value="transplanted">Transplanted</option><option value="growing">Growing</option><option value="ready_to_harvest">Ready to harvest</option><option value="harvesting">Harvesting</option></select></label></div><label className="check"><input type="checkbox" name="perennial" /> Perennial crop</label><label>Notes<textarea name="notes" rows={2} /></label><button className="primary">Save planting</button></form></Modal>}
  </main>;
}

function Dashboard({ seeds, activePlantings, occupied, onGo }: { seeds: Seed[]; activePlantings: Planting[]; occupied: Set<string>; onGo: (p: Page) => void }) { const low = seeds.filter(s => s.status === "low_stock").length; return <><div className="intro"><div><h2>Your farm, in view.</h2><p>Keep a calm, accurate picture of every bed, seed packet, and growing crop.</p></div><button className="primary" onClick={() => onGo("Plantings")}>+ Record planting</button></div><div className="metrics"><Metric label="SEED VARIETIES" value={seeds.filter(s => s.status === "in_stock").length} sub={`${low} low stock`} /><Metric label="CURRENT PLANTINGS" value={activePlantings.length} sub={`${occupied.size} zones occupied`} /><Metric label="PLANTING ZONES" value={zones.length} sub={`${zones.length - occupied.size} available`} /></div><section className="upcoming"><p className="eyebrow">UPCOMING</p><h3>Ready for the next season.</h3><p>Planting recommendations and weekly farm tasks will appear here.</p></section><section className="overview"><div><p className="eyebrow">FARM OVERVIEW</p><h3>{occupied.size ? `${occupied.size} zones are active` : "No active zones yet"}</h3><p>Start by recording what is already growing, even when dates are approximate or unknown.</p></div><button className="outline" onClick={() => onGo("Farm Map")}>View farm map →</button></section></> }
function Metric({ label, value, sub }: { label: string; value: number; sub: string }) { return <div className="metric"><p>{label}</p><strong>{value}</strong><span>{sub}</span></div>; }
function MapView({ selected, onSelect, occupied, plantings, onAdd }: { selected: string; onSelect: (s: string) => void; occupied: Set<string>; plantings: Planting[]; onAdd: () => void }) { const zone = zones.find(z => z.code === selected)!; const current = plantings.filter(p => p.zone === selected); return <><div className="page-intro"><div><h2>Farm map</h2><p>Development geometry only. Zone codes are permanent; the surveyed map can replace this view later.</p></div><span className="legend"><i></i> Occupied zone</span></div><div className="map-layout"><div className="map-card"><div className="map-header"><span>CLICK A ZONE TO INSPECT</span><span>{zones.length} planting zones</span></div><ZoneGrid selected={selected} onSelect={onSelect} occupied={occupied} /></div><div className="details"><p className="eyebrow">ZONE DETAILS</p><h2>{zone.code}</h2><h3>{zone.name}</h3><div className="dimensions"><span><b>{zone.width} m</b> width</span><span><b>{zone.length} m</b> length</span><span><b>{zone.width * zone.length} m²</b> area</span></div><hr /><p className="eyebrow">CURRENT PLANTINGS</p>{current.length ? current.map(p => <div className="planting-mini" key={p.id}><strong>{p.crop}{p.variety ? ` · ${p.variety}` : ""}</strong><span><StatusPill status={p.status} /> {p.date || "Date unknown"}</span></div>) : <p className="muted">Nothing recorded here yet.</p>}<button className="primary full" onClick={onAdd}>+ Add planting</button><p className="history">Previous planting history will remain here after crops are finished or removed.</p></div></div></> }
function PlantingsView({ plantings, onAdd, onEnd, onSelect }: { plantings: Planting[]; onAdd: () => void; onEnd: (id: number, s: "finished" | "removed") => void; onSelect: (z: string) => void }) { return <><div className="page-intro"><div><h2>What’s growing</h2><p>Record planned, existing, and active crops. Finished records stay in the farm’s history.</p></div><button className="primary" onClick={onAdd}>+ Record planting</button></div>{plantings.length === 0 ? <div className="empty"><span>⌁</span><h2>Start with what you can see.</h2><p>Add an existing planting for crops already in the ground. Dates can be unknown.</p><button className="primary" onClick={onAdd}>Record first planting</button></div> : <div className="table-card"><table><thead><tr><th>Crop</th><th>Zone</th><th>Planted</th><th>Status</th><th></th></tr></thead><tbody>{plantings.map(p => <tr key={p.id}><td><strong>{p.crop}</strong><small>{p.variety || p.family || "—"}</small></td><td><button className="zone-link" onClick={() => onSelect(p.zone)}>{p.zone}</button></td><td>{p.date || "Unknown"}<small>{p.precision}</small></td><td><StatusPill status={p.status} /></td><td>{activeStatuses.includes(p.status) && <details><summary>•••</summary><button onClick={() => onEnd(p.id, "finished")}>Finish</button><button onClick={() => onEnd(p.id, "removed")}>Remove</button></details>}</td></tr>)}</tbody></table></div>}</> }
function SeedsView({ seeds, setSeeds, onAdd }: { seeds: Seed[]; setSeeds: React.Dispatch<React.SetStateAction<Seed[]>>; onAdd: () => void }) { const setStatus = (id: number, status: Seed["status"]) => setSeeds(s => s.map(x => x.id === id ? { ...x, status, active: status !== "discontinued" } : x)); return <><div className="page-intro"><div><h2>Seed inventory</h2><p>Your stored varieties. Seed inventory is separate from what is planted on the farm.</p></div><button className="primary" onClick={onAdd}>+ Add seed</button></div><div className="table-card"><table><thead><tr><th>Seed</th><th>Crop family</th><th>Quantity</th><th>Status</th><th></th></tr></thead><tbody>{seeds.map(s => <tr key={s.id}><td><strong>{s.crop}</strong><small>{s.variety || "No variety recorded"}</small></td><td>{s.family || "—"}</td><td>—</td><td><StatusPill status={s.status} /></td><td><details><summary>•••</summary><button onClick={() => setStatus(s.id, "in_stock")}>Mark in stock</button><button onClick={() => setStatus(s.id, "low_stock")}>Mark low stock</button><button onClick={() => setStatus(s.id, "out_of_stock")}>Mark out of stock</button><button onClick={() => setStatus(s.id, "discontinued")}>Discontinue</button><button className="danger" onClick={() => setSeeds(x => x.filter(item => item.id !== s.id))}>Delete</button></details></td></tr>)}</tbody></table></div></> }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>; }
